### ISSUE TITLE
ZXing barcode scanner app not found in Google Play Store

### ISSUE THREAD

**Issue by bishinew** [zxing/zxing#1133] opened 2019-02-08 17:28 UTC
Android app ZXing Barcode Scanner is not available in Google Play Store. What happened?

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

Thanks

**Comment by srowen** [comment] 2019-02-08 18:08
Hm! That's weird. I didn't do anything to it. Will look into it, but you can always get the .APK here if you need it.

**Comment by srowen** [comment] 2019-02-08 19:04
Says it was removed for violating some terms of the developer program. Comical as it hasn't been updated in a long time and has been around in the same form for a decade. I will try to get more info on what the issue is

**Comment by alexsandro** [comment] 2019-02-08 19:31
we are facing with this same error on try download it. I made a search on google play, and find a similar app with the same name, maybe this causes some problem with your app.
https://play.google.com/store/apps/details?id=com.qrcodescanner.barcodescanner

**Comment by bishinew** [comment] 2019-02-08 19:47
Such a popular app! Please get it back in Google Play Store as soon as possible. Thanks.

**Comment by srowen** [comment] 2019-02-08 19:54
There are a lot of clones. You can use them but be careful that many have ads and a few might have malware. You can download and install the .APK from here thoigh

**Comment by bishinew** [comment] 2019-02-08 20:01
Our app suggests users to download this one in the Play Store. The link is broken. There are so many downloads. You guys should keep support it. Thanks.

**Comment by srowen** [comment] 2019-02-08 20:10
Yes, to be clear, I didn't do any of this. Somebody at Google did, and I don't know why yet.
The app is no longer developed, but that is a separate issue. It should remain published indefinitely.

**Comment by bishinew** [comment] 2019-02-08 20:26
No new development is fine. 

Please meet Google Play Store requirements and stay published.

Thanks

**Comment by srowen** [comment] 2019-02-08 20:34
... to be clear again, the app hasn't changed in a long time. This is almost certainly an error on Play.

**Comment by bishinew** [comment] 2019-02-08 20:38
Understand what you mean.

The issue is "the app hasn't changed in a long time".

The play store has some new requirements such as privacy, rating etc. Please check if the app meet those requirements.

Thanks

**Comment by vrtareg** [comment] 2019-02-09 11:24
Hi
Just found this 
https://play.google.com/store/apps/details?id=com.srowen.bs.android
Is this same or different one?

**Comment by srowen** [comment] 2019-02-09 15:42
While it's not the same exactly, that is an app that I also created, which is now open source. It is a work-alike.

**Comment by srowen** [comment] 2019-02-10 17:51
It looks like it won't be republished. The problem concerns SMS-related permissions. To request an exemption and allow these permissions, it's required to submit a bunch of info and a new version of the app. The app can't be uploaded anymore though. I'm afraid this may be the end of the line for the app on Play store.

The .apk can still be installed manually, and is available at https://github.com/zxing/zxing/releases/tag/BS-4.7.8 Third parties are welcome to redistribute this .apk.

For now, the 'plus' app remains available, and is a very similar work-alike app, which responds to the same Intents:
https://play.google.com/store/apps/details?id=com.srowen.bs.android&hl=en_US

**Comment by bishinew** [comment] 2019-02-10 21:20
Just explain to Google Play Store why you need SMS permission by filling the form. If the usage is proper, they will give the green light.

Do you consider transferring the app to someone else to maintain? 

Thanks

**Comment by srowen** [comment] 2019-02-10 21:58
It requires resubmitting the app and that can't be done. The app can't be transferred and it wouldn't help anyway. It is still available just unfortunately not on Play, but it has been unsupported for a while anyway.

**Comment by sw-ericgrehan** [comment] 2019-02-12 12:56
Hi how do I integrate this 'plus' app into my app? I cannot edit IntentIntegrator.java to remove any reference to the removed Play store app. Thanks

**Comment by srowen** [comment] 2019-02-12 13:07
See IntentIntegrator.java in the project for a full integration; you can target both packages for both apps so that either one works.

**Comment by sw-ericgrehan** [comment] 2019-02-12 14:23
Thank you, I got that to work. Should I beware of any differences between the plus version and the other discontinued version? Tks

**Comment by mhoberhausen** [comment] 2019-02-12 15:16
@srowen when attempting to use the com.srowen.bs.android or com.srowen.bs.android.simple packages, the .SCAN intent is not present. What change will need to be made in order to use one of these packages along with the IntentIntegrator.java class?

Thanks!

**Comment by srowen** [comment] 2019-02-12 15:40
Oh, it's the same Intent. That doesn't change at all. If you are targeting specific packages, you can target both the com.google... and com.srowen... packages. You don't have to target packages, but it can be useful to make sure some random third-party app doesn't intercept the Intent.

**Comment by mhoberhausen** [comment] 2019-02-12 15:57
Not sure what caused it to not work but I copied the latest IntentIntegrator.java and now everything works as expected! Thanks for the info

**Comment by sw-ericgrehan** [comment] 2019-02-13 09:52
Just a thought, but is this plus Scanner going to disappear anytime soon as well or is it compliant?Tks

**Comment by tylerszabo** [comment] 2019-02-16 07:39
It's still available in F-Droid: https://f-droid.org/app/com.google.zxing.client.android

@srowen - is that version kept up-to-date with bug fixes?

**Comment by srowen** [comment] 2019-02-16 15:37
No that has always been a third party updating it. The .apk is still distributed here

**Comment by raphmte** [comment] 2019-02-19 19:34
> 
> 
> Not sure what caused it to not work but I copied the latest IntentIntegrator.java and now everything works as expected! Thanks for the info

@mhoberhausen can you show me how you solved it? I'm trying to change here but it always says that I need to install the same app already having it installed.

**Comment by xvzf** [comment] 2019-02-21 14:54
Hi!

So what do you guys think about removing the SMS related parts? It could be on the Play-Store again just with kind of limited functionality!

**Comment by srowen** [comment] 2019-02-21 14:58
It wouldn't change the fact that it can't be uploaded as it targets older API levels. It might get reinstated as a special case but it's out of my hands right now; the app really is not maintained at this point.

**Comment by 532910** [comment] 2019-02-24 19:48
Could you clarify the status of the Barcode Scanners.

https://github.com/zxing/zxing
is under development, but no longer available in Google Play Store

https://github.com/srowen/zxing-bsplus
is archived, but available in Google Play Store

**Comment by srowen** [comment] 2019-02-24 23:07
Apps: neither is under development at all. They can't even be uploaded at this point. Yes, unfortunately the Barcode Scanner app doesn't look like it's coming back as it uses old SMS permissions.

Project: neither is under development. I have left this one unarchived as there are occasional (non-Android) patches submitted, which I'll still look at.

**Comment by srowen** [comment] 2019-02-25 22:52
Good news - the app is back.
https://play.google.com/store/apps/details?id=com.google.zxing.client.android

It turned out it was mostly a misunderstanding. The problem was with one of the much older releases that was still live for old devices. That was removed, but the releases for the past few years are still there including the most recent one.

**Closed by srowen** 2019-02-25 22:52 UTC

**Comment by jesus2099** [comment] 2026-02-01 17:06
Now it’s no longer available again.
Why not remove SMS features?
I don’t even know where they are in the app?
