### ISSUE TITLE
DataMatrixWriter: dimensions not used

### ISSUE THREAD

**Issue by cyrilfr** [zxing/zxing#930] opened 2017-12-20 11:10 UTC
#271  I'm using ZXing Java SE 3.3.1 from the central maven repo and I still have this issue. What's the workaround?

Example:
```
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.datamatrix.DataMatrixWriter;

int width = 300;
int height = 300;
String content = "Buu";
String filename = "code.png";
String extension = "png";

FileOutputStream stream = new FileOutputStream(new File(filename));
DataMatrixWriter writer = new DataMatrixWriter();
BitMatrix matrix = writer.encode(content, BarcodeFormat.DATA_MATRIX, width, height);
MatrixToImageWriter.writeToStream(matrix, extension, stream);
```
Result:
![Buu](https://img15.hostingpics.net/pics/274067code.png)

Expected:
![Buu](https://img15.hostingpics.net/pics/914385code.png)

**Edit**
I also don't see the need to pass `BarcodeFormat.DATA_MATRIX` to `encode()`. Could the `DataMatrixWriter` writes other kind of barcodes than DataMatrix?

**Comment by axxel** [comment] 2017-12-20 11:18
See also #836.

**Comment by kaungmyathtun** [comment] 2017-12-20 15:08
Issue

**Comment by srowen** [comment] 2017-12-20 16:31
Yes, duplicate of https://github.com/zxing/zxing/issues/836

**Closed by srowen** 2017-12-20 16:31 UTC
