### ISSUE TITLE
A code 128 that Zxing cannot scan it out but Zbar can quickly scan it out

### ISSUE THREAD

**Issue by drakeet** [zxing/zxing#595] opened 2016-05-10 15:52 UTC
### Bug Reports

As provided by the bar code picture, it's a `code 128`, `Zxing` can not scan it out, or work slowly, and `ZBar` can quickly scan it out. Please check out what's going on, look forward to improving.

![image](https://cloud.githubusercontent.com/assets/5214214/15153168/ca1b72a8-170a-11e6-9be9-845d4c5fb020.png)

**Comment by srowen** [comment] 2016-05-10 16:16
That looks like an invalid barcode, or at least out of tolerances. Even if it's not, it's not a bug that a particular image decodes. There is no ongoing development in this project, so I would have to close this unless you are opening a clean PR.

**Closed by srowen** 2016-05-10 16:16 UTC
