### ISSUE TITLE
Camera flipped on Nexus 5x

### ISSUE THREAD

**Issue by markdrake** [zxing/zxing#645] opened 2016-08-03 03:12 UTC
Hey there,

The library works just fine but my preview always display my image upside down from my camera. It doesn't affect the ability to read QR Codes but it seems to be a known issue within the library: https://github.com/zxing/zxing/issues/484

Have you seen this issue and know how to fix it?

Best regards.

**Comment by sahir** [comment] 2016-08-03 04:36
@markdrake this issue already fixed

https://github.com/zxing/zxing/commit/f58271e14651c42a6ea2cf1d17dd1281206bf898

**Comment by srowen** [comment] 2016-08-08 08:10
... and/or duplicate of https://github.com/zxing/zxing/issues/576

**Closed by srowen** 2016-08-08 08:10 UTC
