### ISSUE TITLE
"Search contents" button in SearchBookContentsActivity not necessary

### ISSUE THREAD

**Issue by parsg** [zxing/zxing#383] opened 2015-05-14 02:06 UTC
The search input is given from the keyboard and on clicking the Done button from keyboard, results are directly displayed without clicking the Search Contents button

**Comment by drewdrewcarlstedt** [comment] 2015-05-14 02:39
Test Name: Share Activity	Version: 1

Severity (Fatal, Serious, Minor): Minor

Type: (Coding Error, Design Issue, Suggestion, Documentation): BlackBox/Acceptance

Summary: Unnecessary button "Search contents"
Able to be reproduced? (Yes/No): No

What is the problem and how can it be reproduced?

There was no need of the this button. From keyboard when done was pressed the result were displaying. So it is Unnecessary button "Search contents"

     Reported By: Shreya Gorde	Date: 04/9/2015
~~~~~~~~~~~~~~~~~~~~~ DEVELOPMENT TEAM ONLY ~~~~~~~~~~~~~~~~~~~~~

Functional Area: ____________________________	Assigned To: ____________________

Comments: ___________________________________________________________________________
___________________________________________________________________________

Status (Open/Closed): _____________________	Priority (1-5): __________________

Resolution (Pending, Fixed, Irreproducible, Reassigned, As Intended, Unfixable, Withdrawn, Requesting More Information, Disagree with Suggestion): ___________________________

Resolved By: _______________________	Date: ________________

Tested By: _________________________	Date: ________________

Fixed Version Number: ______________________

**Closed** 2015-05-14 07:49 UTC
