### ISSUE TITLE
Camera flipped upside down on nexus 5x

### ISSUE THREAD

**Issue by echarny** [zxing/zxing#552] opened 2016-02-05 16:48 UTC
Hi,
The camera is flipped upside down on nexus 5x so when a barcode is read it reads in reverse/ not correct number. 

According to this article (http://www.theverge.com/2015/11/9/9696774/google-nexus-5x-upside-down-camera) it is because the app is using a deprecated camera api.

**Comment by srowen** [comment] 2016-02-05 18:15
The app is OK and I'm unable to reproduce it. This is a duplicate anyway. If you don't have a change to suggest I'd have to close this. Camera API is not deprecated in 5.x, but even if it were it is supposed to be implemented correctly right?

**Closed by srowen** 2016-02-05 18:15 UTC

**Comment by echarny** [comment] 2016-02-05 18:40
Hi,I am running android 6.0.1 not 5.x.
This is the post on reddit that is linked to in the verge article I linked earlier.

[–]etalvala 53 points  3 months ago  Hi - Tech lead for Android's camera framework here.Image sensors on a compliant Android device can be mounted in one of two ways. Most devices use one way, so a lot of camera apps have never been tested on devices that pick the other way.Because of manufacturing reasons, we needed to mount the Nexus 5X main sensor in the less-common (reverse landscape) orientation - the wires from the sensor chip wouldn't have fit otherwise.Unfortunately, our old camera API (which is deprecated, but most apps still use it) isn't terribly user-friendly, and requires application developers to explicitly set the preview rotation. On most devices, though, it turns out the default rotation is correct for a forced-landscape app, so many apps never call the display orientation method.The new camera2 API handles the rotation automatically for developers, but until they move to the new API, apps need to use the boilerplate we have in the developer docs to check the sensor and UI orientation, and apply the right rotation: http://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation(int)We tried to work out a way to adjust the default so that apps wouldn't have to deal with this, but unfortunately changing it would have broken apps that do call this method.This is also why a number of apps showed upside down preview on the Nexus 6 front-facing camera last year - it's also in the less-common orientation. But far fewer apps support the front-facing camera than the back-facing one, so it was less of an issue than it is for Nexus 5X.So if you do see apps with upside-down camera preview on Nexus 5X, please let the developers know about this - Android's developer relations folks are trying to reach out to apps as we find them, and LG is also helping out, but it might take a bit before everyone's up to speed on this issue.   
   - permalink
   - Nexus5X Marshmallow camera problem • /r/Android

|   |
|   |  |   |   |   |   |   |
| Nexus5X Marshmallow camera problem • /r/AndroidAs a developer of popular QR & Barcode Scanner: https://play.google.com/store/apps/details?id=com.gamma.scan I received this from LG by... |
|  |
| View on www.reddit.com | Preview by Yahoo |
|  |
|   |




I would highly appreciate it if you can make this addition
    On Friday, February 5, 2016 1:17 PM, Sean Owen <notifications@github.com> wrote:
 
 

 Closed #552.—

**Comment by srowen** [comment] 2016-02-05 22:39
Did you read the source? Already how it works.
