### ISSUE TITLE
First selected app for share is chosen as default and cannot be reverted.

### ISSUE THREAD

**Issue by parsg** [zxing/zxing#384] opened 2015-05-14 02:10 UTC
e.g: When selected record from history, then share it via email, mail related applications need to be displayed.

**Comment by drewdrewcarlstedt** [comment] 2015-05-14 02:40
Test Name: History Activity	Version: 1

Severity (Fatal, Serious, Minor): Minor

Type: (Coding Error, Design Issue, Suggestion, Documentation): BlackBox/Acceptance

Summary:If contact is selected by mistake instead of email then it remains as default for share via email. Which is wrong it should let user to revert his/her choice of app.

Able to be reproduced? (Yes/No): No

What is the problem and how can it be reproduced?

If contact is selected by mistake instead of email then it remains as default for share via email. Which is wrong it should let user to revert his/her choice of app.


     Reported By: Pooja Raghoji 	Date: 04/04/2015
~~~~~~~~~~~~~~~~~~~~~ DEVELOPMENT TEAM ONLY ~~~~~~~~~~~~~~~~~~~~~

Functional Area: ____________________________	Assigned To: ____________________

Comments: ___________________________________________________________________________
___________________________________________________________________________

Status (Open/Closed): _____________________	Priority (1-5): __________________

Resolution (Pending, Fixed, Irreproducible, Reassigned, As Intended, Unfixable, Withdrawn, Requesting More Information, Disagree with Suggestion): ___________________________

Resolved By: _______________________	Date: ________________

Tested By: _________________________	Date: ________________

Fixed Version Number: ______________________

**Closed** 2015-05-14 07:49 UTC
