### ISSUE TITLE
Broken Documentation Links

### ISSUE THREAD

**Issue by Gamecock** [zxing/zxing#1076] opened 2018-09-25 15:55 UTC
Link to ZXing Core documentation is broken, returns 404.

https://zxing.github.io/zxing/core/index.html

**Comment by srowen** [comment] 2018-09-25 16:32
Yep, duplicate of https://github.com/zxing/zxing/issues/1052 . Basically I don't know how to get it to not generate links to module pages that don't exist, and don't have motivation to find out as the only really important docs are the javadoc. Open a PR if you know how to do it.

**Closed by srowen** 2018-09-25 16:32 UTC
