### ISSUE TITLE
Screen in portrait mode

### ISSUE THREAD

**Issue by pandans** [zxing/zxing#493] opened 2015-11-08 14:41 UTC
Many apps used in portrait mode only, buy this lib almost support Land mode only, I had improved a version in my app used portrait（change cameraManager and preview）,but i found the scan may slow the land mode. 
so can you support land mode official ! thank you!!

**Comment by srowen** [comment] 2015-11-08 15:42
Duplicate of #111 but this project does not take requests anyway, only PRs

**Closed by srowen** 2015-11-08 15:42 UTC
