### ISSUE TITLE
BUG Encoding string contains '-' character, problem with C40 Encoding

### ISSUE THREAD

**Issue by stackhchad** [zxing/zxing#1486] opened 2022-01-19 22:44 UTC
Hi,

I forced using C40 Encoding : ` context.setForce(true);`
The problem occurs when i run this test with "Hello-Google" or "--" : 

```
public final class DataMatrixWriterTestCase extends Assert {

  @Test
  public void testDataMatrixImageWriter() {

    Map<EncodeHintType,Object> hints = new EnumMap<>(EncodeHintType.class);
    hints.put(EncodeHintType.DATA_MATRIX_SHAPE, SymbolShapeHint.FORCE_SQUARE);
    hints.put(EncodeHintType.FORCE_C40, true);

    int bigEnough = 64;
    DataMatrixWriter writer = new DataMatrixWriter();
    BitMatrix matrix = writer.encode("Hello-Google", BarcodeFormat.DATA_MATRIX, bigEnough, bigEnough, hints);
    assertNotNull(matrix);
    assertTrue(bigEnough >= matrix.getWidth());
    assertTrue(bigEnough >= matrix.getHeight());
  }
```
i got this error : 

```
> java.lang.IllegalArgumentException: Can't find a symbol arrangement that matches the message. Data codewords: 1559

	at com.google.zxing.datamatrix.encoder.SymbolInfo.lookup(SymbolInfo.java:148)
	at com.google.zxing.datamatrix.encoder.EncoderContext.updateSymbolInfo(EncoderContext.java:136)
	at com.google.zxing.datamatrix.encoder.C40Encoder.encode(C40Encoder.java:39)
	at com.google.zxing.datamatrix.encoder.HighLevelEncoder.encodeHighLevel(HighLevelEncoder.java:194)
	at com.google.zxing.datamatrix.DataMatrixWriter.encode(DataMatrixWriter.java:88)
	at com.google.zxing.datamatrix.DataMatrixWriterTestCase.testDataMatrixImageWriter(DataMatrixWriterTestCase.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code -1
```

Thanks!.

**Comment by srowen** [comment] 2022-01-19 23:14
Sounds like a legit bug - dash is allowed in C40 - but I have no idea how to debug or fix that. PRs welcome!

**Comment by srowen** [comment] 2022-01-22 13:43
Alex has a good question - where are you getting FORCE_C40? I don't see that in the project

**Comment by stackhchad** [comment] 2022-01-24 08:56
Hi,
To force C40 Encoding, i added FORCE_C40 to EncodeHintType, and in DataMatrixWriter i changed encode function :

 ```
public BitMatrix encode(String contents, BarcodeFormat format, int width, int height, Map<EncodeHintType,?> hints) {
    if (contents.isEmpty()) {
      throw new IllegalArgumentException("Found empty contents");
    }
    if (format != BarcodeFormat.DATA_MATRIX) {
      throw new IllegalArgumentException("Can only encode DATA_MATRIX, but got " + format);
    }
    if (width < 0 || height < 0) {
      throw new IllegalArgumentException("Requested dimensions can't be negative: " + width + 'x' + height);
    }
    // Try to get force shape & min / max size
    SymbolShapeHint shape = SymbolShapeHint.FORCE_NONE;
    Dimension minSize = null;
    Dimension maxSize = null;
    **Boolean forceC40 = null;**
    if (hints != null) {
      SymbolShapeHint requestedShape = (SymbolShapeHint) hints.get(EncodeHintType.DATA_MATRIX_SHAPE);
      if (requestedShape != null) {
        shape = requestedShape;
      }
      @SuppressWarnings("deprecation")
      Dimension requestedMinSize = (Dimension) hints.get(EncodeHintType.MIN_SIZE);
      if (requestedMinSize != null) {
        minSize = requestedMinSize;
      }
      @SuppressWarnings("deprecation")
      Dimension requestedMaxSize = (Dimension) hints.get(EncodeHintType.MAX_SIZE);
      if (requestedMaxSize != null) {
        maxSize = requestedMaxSize;
      }
      **Boolean c40Force = (Boolean) hints.get(EncodeHintType.FORCE_C40);
      if(c40Force !=null) {
        forceC40 = c40Force;
      }**
    }
    //1. step: Data encodation
    **String encoded = HighLevelEncoder.encodeHighLevel(contents, shape, minSize, maxSize, forceC40);**
    SymbolInfo symbolInfo = SymbolInfo.lookup(encoded.length(), shape, minSize, maxSize, true);
    //2. step: ECC generation
    String codewords = ErrorCorrection.encodeECC200(encoded, symbolInfo);
    //3. step: Module placement in Matrix
    DefaultPlacement placement =
        new DefaultPlacement(codewords, symbolInfo.getSymbolDataWidth(), symbolInfo.getSymbolDataHeight());
    placement.place();
    //4. step: low-level encoding
    return encodeLowLevel(placement, symbolInfo, width, height);
  }
```

And in DatamatrixGenerator, i changed generateMatrix function :

 ```
private static BitMatrix generateMatrix(String contents, int width, int height) throws Code2DException {
        Map<EncodeHintType, Object> hints = new EnumMap<EncodeHintType, Object>(EncodeHintType.class);
        hints.put(EncodeHintType.CHARACTER_SET, StandardCharsets.ISO_8859_1.name());
        hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.M); //15%
        hints.put(EncodeHintType.DATA_MATRIX_SHAPE, SymbolShapeHint.FORCE_SQUARE);
        hints.put(EncodeHintType.MARGIN, QUIET_ZONE_SIZE); /* default = 4 */
        **hints.put(EncodeHintType.FORCE_C40, true);**
        return new DataMatrixWriter().encode(contents, BarcodeFormat.DATA_MATRIX, width, height, hints);
    }
```
I put my modifications in the code between ** .

And this is how it look "encodeHighLevel" and "lookAheadTest" functions: 

```
  public static String encodeHighLevel(String msg,
                                       SymbolShapeHint shape,
                                       Dimension minSize,
                                       Dimension maxSize) {
    **return encodeHighLevel(msg,shape, minSize, maxSize, false);**
  }

  public static String encodeHighLevel(String msg,
      SymbolShapeHint shape,
      Dimension minSize,
      Dimension maxSize,
      Boolean forceC40) {
    //the codewords 0..255 are encoded as Unicode characters
    Encoder[] encoders = {
        new ASCIIEncoder(), new C40Encoder(), new TextEncoder(),
        new X12Encoder(), new EdifactEncoder(),  new Base256Encoder()
    };

    EncoderContext context = new EncoderContext(msg);
    context.setSymbolShape(shape);
    context.setSizeConstraints(minSize, maxSize);
    context.setForce(forceC40);

    if (msg.startsWith(MACRO_05_HEADER) && msg.endsWith(MACRO_TRAILER)) {
      context.writeCodeword(MACRO_05);
      context.setSkipAtEnd(2);
      context.pos += MACRO_05_HEADER.length();
    } else if (msg.startsWith(MACRO_06_HEADER) && msg.endsWith(MACRO_TRAILER)) {
      context.writeCodeword(MACRO_06);
      context.setSkipAtEnd(2);
      context.pos += MACRO_06_HEADER.length();
    }

    int encodingMode = ASCII_ENCODATION; //Default mode
    while (context.hasMoreCharacters()) {
      encoders[encodingMode].encode(context);
      if (context.getNewEncoding() >= 0) {
        encodingMode = context.getNewEncoding();
        context.resetEncoderSignal();
      }
    }
    int len = context.getCodewordCount();
    context.updateSymbolInfo();
    int capacity = context.getSymbolInfo().getDataCapacity();
    if (len < capacity &&
        encodingMode != ASCII_ENCODATION &&
        encodingMode != BASE256_ENCODATION &&
        encodingMode != EDIFACT_ENCODATION) {
      context.writeCodeword('\u00fe'); //Unlatch (254)
    }
    //Padding
    StringBuilder codewords = context.getCodewords();
    if (codewords.length() < capacity) {
      codewords.append(PAD);
    }
    while (codewords.length() < capacity) {
      codewords.append(randomize253State(codewords.length() + 1));
    }

    return context.getCodewords().toString();
  }

  **static int lookAheadTest(CharSequence msg, int startpos, int currentMode, Boolean force)** {

    **if(force) {
      return C40_ENCODATION;
    }**
    if (startpos >= msg.length()) {
      return currentMode;
    }
    float[] charCounts;
    //step J
    if (currentMode == ASCII_ENCODATION) {
      charCounts = new float[]{0, 1, 1, 1, 1, 1.25f};
    } else {
      charCounts = new float[]{1, 2, 2, 2, 2, 2.25f};
      charCounts[currentMode] = 0;
    }

    int charsProcessed = 0;
    while (true) {
      //step K
      if ((startpos + charsProcessed) == msg.length()) {
        int min = Integer.MAX_VALUE;
        byte[] mins = new byte[6];
        int[] intCharCounts = new int[6];
        min = findMinimums(charCounts, intCharCounts, min, mins);
        int minCount = getMinimumCount(mins);

        if (intCharCounts[ASCII_ENCODATION] == min) {
          return ASCII_ENCODATION;
        }
        if (minCount == 1 && mins[BASE256_ENCODATION] > 0) {
          return BASE256_ENCODATION;
        }
        if (minCount == 1 && mins[EDIFACT_ENCODATION] > 0) {
          return EDIFACT_ENCODATION;
        }
        if (minCount == 1 && mins[TEXT_ENCODATION] > 0) {
          return TEXT_ENCODATION;
        }
        if (minCount == 1 && mins[X12_ENCODATION] > 0) {
          return X12_ENCODATION;
        }
        return C40_ENCODATION;
      }

      char c = msg.charAt(startpos + charsProcessed);
      charsProcessed++;

      //step L
      if (isDigit(c)) {
        charCounts[ASCII_ENCODATION] += 0.5f;
      } else if (isExtendedASCII(c)) {
        charCounts[ASCII_ENCODATION] = (float) Math.ceil(charCounts[ASCII_ENCODATION]);
        charCounts[ASCII_ENCODATION] += 2.0f;
      } else {
        charCounts[ASCII_ENCODATION] = (float) Math.ceil(charCounts[ASCII_ENCODATION]);
        charCounts[ASCII_ENCODATION]++;
      }

      //step M
      if (isNativeC40(c)) {
        charCounts[C40_ENCODATION] += 2.0f / 3.0f;
      } else if (isExtendedASCII(c)) {
        charCounts[C40_ENCODATION] += 8.0f / 3.0f;
      } else {
        charCounts[C40_ENCODATION] += 4.0f / 3.0f;
      }

      //step N
      if (isNativeText(c)) {
        charCounts[TEXT_ENCODATION] += 2.0f / 3.0f;
      } else if (isExtendedASCII(c)) {
        charCounts[TEXT_ENCODATION] += 8.0f / 3.0f;
      } else {
        charCounts[TEXT_ENCODATION] += 4.0f / 3.0f;
      }

      //step O
      if (isNativeX12(c)) {
        charCounts[X12_ENCODATION] += 2.0f / 3.0f;
      } else if (isExtendedASCII(c)) {
        charCounts[X12_ENCODATION] += 13.0f / 3.0f;
      } else {
        charCounts[X12_ENCODATION] += 10.0f / 3.0f;
      }

      //step P
      if (isNativeEDIFACT(c)) {
        charCounts[EDIFACT_ENCODATION] += 3.0f / 4.0f;
      } else if (isExtendedASCII(c)) {
        charCounts[EDIFACT_ENCODATION] += 17.0f / 4.0f;
      } else {
        charCounts[EDIFACT_ENCODATION] += 13.0f / 4.0f;
      }

      // step Q
      if (isSpecialB256(c)) {
        charCounts[BASE256_ENCODATION] += 4.0f;
      } else {
        charCounts[BASE256_ENCODATION]++;
      }

      //step R
      if (charsProcessed >= 4) {
        int[] intCharCounts = new int[6];
        byte[] mins = new byte[6];
        findMinimums(charCounts, intCharCounts, Integer.MAX_VALUE, mins);
        int minCount = getMinimumCount(mins);

        if (intCharCounts[ASCII_ENCODATION] < intCharCounts[BASE256_ENCODATION]
            && intCharCounts[ASCII_ENCODATION] < intCharCounts[C40_ENCODATION]
            && intCharCounts[ASCII_ENCODATION] < intCharCounts[TEXT_ENCODATION]
            && intCharCounts[ASCII_ENCODATION] < intCharCounts[X12_ENCODATION]
            && intCharCounts[ASCII_ENCODATION] < intCharCounts[EDIFACT_ENCODATION]) {
          return ASCII_ENCODATION;
        }
        if (intCharCounts[BASE256_ENCODATION] < intCharCounts[ASCII_ENCODATION]
            || (mins[C40_ENCODATION] + mins[TEXT_ENCODATION] + mins[X12_ENCODATION] + mins[EDIFACT_ENCODATION]) == 0) {
          return BASE256_ENCODATION;
        }
        if (minCount == 1 && mins[EDIFACT_ENCODATION] > 0) {
          return EDIFACT_ENCODATION;
        }
        if (minCount == 1 && mins[TEXT_ENCODATION] > 0) {
          return TEXT_ENCODATION;
        }
        if (minCount == 1 && mins[X12_ENCODATION] > 0) {
          return X12_ENCODATION;
        }
        if (intCharCounts[C40_ENCODATION] + 1 < intCharCounts[ASCII_ENCODATION]
            && intCharCounts[C40_ENCODATION] + 1 < intCharCounts[BASE256_ENCODATION]
            && intCharCounts[C40_ENCODATION] + 1 < intCharCounts[EDIFACT_ENCODATION]
            && intCharCounts[C40_ENCODATION] + 1 < intCharCounts[TEXT_ENCODATION]) {
          if (intCharCounts[C40_ENCODATION] < intCharCounts[X12_ENCODATION]) {
            return C40_ENCODATION;
          }
          if (intCharCounts[C40_ENCODATION] == intCharCounts[X12_ENCODATION]) {
            int p = startpos + charsProcessed + 1;
            while (p < msg.length()) {
              char tc = msg.charAt(p);
              if (isX12TermSep(tc)) {
                return X12_ENCODATION;
              }
              if (!isNativeX12(tc)) {
                break;
              }
              p++;
            }
            return C40_ENCODATION;
          }
        }
      }
    }
  }

```

Thanks!

**Comment by AlexGeller1** [comment] 2022-01-24 13:47
@Sean: This is not a bug (the test passes fine in the current unmodified implementation).
@stackhchad : You need to debug your changes. In particular I would trace calls and values inside C40Encoder.encode().
You return C40_ENCODATION from HighLevelEncoder.lookAheadTest() under all circumstances but it may not work in all cases. In other words, the calling code may not be able to cope with that.
C40 encodation is a bit tricky in particular at the end of the input. Some input that consists solely of C40 encodable characters may for example require the last character to encoded in ASCII encodation. That and other subtilities result in the fact that each character 'c' can end up in up to 4 C40 values (c (native); shift, c; shift, upper shift, c; shift, upper shift, shift, c) and these C40 values are encoded in triplets so that 3 triplets occupy 2 codewords/bytes. The encoder must ensure that the triplets are fully filled before switching mode and the code in C40Encoder.encode() takes care of that in one way or another.
The relevant section of the spec is this:
~~~code
5.2.5 C40 encodation 

The C40 encodation scheme is designed to optimise the encoding of upper-case alphabetic and numeric 
characters but also enables other characters to be encoded by the use of shift characters in conjunction with 
the data character. 
C40 characters are partitioned into 4 subsets. Characters of the first set, called the basic set, are the three 
special shift characters, the space character, and the ASCII characters A-Z and 0-9. They are assigned to a 
single C40 values. Characters of the other sets are assigned to one of the three shift characters, pointing to 
one of the 3 remaining subset, followed by one of the C40 values (see Annex C, Table C.1). 
As a first stage, each data character is converted into a single C40 value or a pair of C40 values. The 
complete string of C40 values is then decomposed into groups of three values (special rules apply if one or 
two values remain at the end, see 5.2.5.2.). Each triplet (C1, C2, C3) is then encoded into a 16-bit value 
according to the formula: (1600 * C1) + (40 * C2) + C3 + 1. Each 16-bit value is then separated into 2 
codewords by taking the most significant 8 bits and the least significant 8 bits. 

5.2.5.1 Switching to and from C40 encodation 
It is possible to switch to C40 encodation from ASCII encodation using the appropriate latch codeword (230). 
Codeword 254 immediately following a pair of codewords in C40 encodation acts as an Unlatch codeword to 
switch back to ASCII encodation. Otherwise, the C40 encodation remains in effect to the end of the data 
encoded in the symbol. 

5.2.5.2 C40 encodation rules 
Each pair of codewords represents a 16-bit value where the first codeword represents the most significant 8 
bits. Three C40 values (C1, C2, C3) shall be encoded as: 
(1600 * C1) + (40 * C2) + C3 + 1 
which produces a value from 1 to 64000. Figure 2 illustrates three C40 values compacted into two codewords. 
Characters in the Shift 1, Shift 2 and Shift 3 sets shall be encoded by first encoding the appropriate shift 
character, and then the C40 value for the data. C40 encodation may be in effect at the end of the symbol's 
codewords which encode data. 
 
The following rules apply when only one or two symbol characters remain in the symbol before the start of the 
error correction codewords: 

a) If two symbol characters remain and three C40 values remain to be encoded (which may include both 
data and shift characters) encode the three C40 values in the last two symbol characters. A final Unlatch 
codeword is not required. 

b) If two symbol characters remain and two C40 values remain to be encoded (the first C40 value may be a 
shift or data character but the second must represent a data character); encode the two remaining C40 
values followed by a pad C40 value of 0 (Shift 1) in the last two symbol characters. A final Unlatch 
codeword again is not required. 

c) If two symbol characters remain and only one C40 value (data character) remains to be encoded, the first 
symbol character is encoded as an Unlatch character and the last symbol character is encoded with the 
data character using the ASCII encodation scheme. 

d) If one symbol character remains and one C40 value (data character) remains to be encoded, the last 
symbol character is encoded with the data character using the ASCII encodation scheme. The Unlatch 
character is not encoded, but is assumed, before the last symbol character. 
In all other cases, either an Unlatch character is used to exit the C40 encodation scheme before the end 
of the symbol, or a larger symbol size is required to encode the data. 

Data characters: "AIM" 
C40 values:14, 22, 26 
Calculate 16-bit value: (1600 * 14) + (40 * 22) + 26 + 1 = 23307 
1st codeword: (16-bit value) div 256 23307 div 256 = 91 
2nd codeword: (16-bit value) mod 256 23307 mod 256 = 11 
Codewords: 91, 11 

Figure 2 — Example of C40 encoding 
5.2.5.3 Use of Upper Shift with C40 
In C40 encodation the Upper Shift character is not a symbology function character but a shift within the 
encodation set. When a data character from the extended ASCII character range is encountered, three or four 
values in C40 encodation need to be encoded according to the following rule: 
IF [ASCII value - 128] is in the Basic Set then: 
[1(Shift 2)] [30(Upper Shift)] [V(ASCII value - 128)] 
ELSE 
[1(Shift 2)] [30(Upper Shift)] [0, 1, or 2(Shift 1, 2, or 3)] [V(ASCII value - 128)] 
In the rule the number in [ ] equates to the C40 values from Annex C.1; V has been used to indicate the 
appropriate C40 value. 
~~~

**Closed** 2022-01-24 14:31 UTC
Labels: bug

**Comment by AlexGeller1** [comment] 2022-01-24 14:38
One more, hopefully helpful, remark. The function that was failing on you updates "SymbolInfo" in the context for the purpose of computing the amount of available codewords/bytes. It failed because the argument to the function (the number of codewords used so far) exceeded the maximum symbol size due to something that went haywire.
You have these two lines:
      context.updateSymbolInfo(curCodewordCount);
      int available = context.getSymbolInfo().getDataCapacity() - curCodewordCount;
The first line context.updateSymbolInfo(curCodewordCount) updates the symbolInfo in the context by searching for the symbol with the smallest capacity whose capacity is the same or larger than curCodewordCount (the number of codewords used so far). Symbols exist with the capacities of 3, 5, 8, 10, 12, 16, 18, 22, 30, 32, 36, 44, 49, 62, 86, 114, 144, 174, 204, 280, 368, 456, 576, 696, 816, 1050, 1304 and 1558.  So that if for example we have curCodewordCount==25 then the function would update symbolInfo with the 9th symbol from this list with a capacity of 30 so that  context.getSymbolInfo().getDataCapacity() will return that value.
The second line (int available = context.getSymbolInfo().getDataCapacity() - curCodewordCount;) then computes the difference between the capacity of the current symbol and the number of codewords used so far so that in our example the value of available would be set to 5 (30-25).
This value is the one that is relevant for the cases 'a' through 'd' in the specification.

**Comment by AlexGeller1** [comment] 2022-01-25 16:08
I had a deeper look at it. If you are OK with it then I will make a PR for it now.

**Comment by stackhchad** [comment] 2022-01-25 16:21
That will help me a lot, thank you for your prompt response.

**Comment by AlexGeller1** [comment] 2022-01-25 20:12
@stackhchad: YW. I just tested with a string that might have been from one of the French government documents. It cannot be completely encoded in C40. The example is this:
IS010000000000000000000000S1118058599124123S21.2.250.1.213.1.4.8 S3FIRST NAMETEST S5MS618-06-1985S713201S4LASTNAMETEST, encoding=ASCII(latch-to-C40),C40(IS010000000000000000000000S1118058599124123S21.2.250.1.213.1.4.8 S3FIRST NAMETEST S5MS618-06-1985S713201S4LASTNAMETES),ASCII(T) size=86
Note that the trailing 'T' is encoded in ASCII and not in C40. 
Do you have a way to validate that the result is what they expect?

**Comment by oehhar** [comment] 2022-01-25 20:39
You may remeber that a Russian Pharma Paper required to use GS (and not FNC1) as GS1 separator. In normal GS1, both are ok. Then, the zint project implemented it and after a month, the requirement was removed. Anyway, nobody could check it, as the transmitted message is the same.

The current requirement remembers me to that. Nobody can really check, if only C40 was used for encodation, as the scanner output is independent on the used encodation.

I personally have lived 7 happy years in France. I always wondered, that requirements are at 200% and reality at 70%. Here, in Germany, it tends to be the opposite. I prefer the French style ;-).

Great that Alex is solving it.
Take care,
Harald

**Comment by AlexGeller1** [comment] 2022-01-25 21:46
Hi Harald,
thanks for being so appreciative. In this particular case the requirement leads to bigger codes, very strange.
Greetings from Strasbourg,
Alex

**Comment by stackhchad** [comment] 2022-01-26 08:57
Hi,
Thank you all for your reactivity.
Thank you Alex for your attention to this matter, i tested your code and it works well.
Best regards,
Zine

**Comment by AlexGeller1** [comment] 2022-01-26 09:52
Thanks for testing! Very good news that it works.
Best regards,
Alex
