### ISSUE TITLE
does not display message "No bookmarks found" when there are no bookmarks in the mobile

### ISSUE THREAD

**Issue by parsg** [zxing/zxing#382] opened 2015-05-14 02:02 UTC
The bug is found in the share activity.

**Comment by drewdrewcarlstedt** [comment] 2015-05-14 02:38
Test Name: Display message “No Bookmark found” 	Version: 1

Severity (Fatal, Serious, Minor): Minor

Type: (Coding Error, Design Issue, Suggestion, Documentation): BlackBox/Acceptance

Summary: Does not display message “No Bookmark found” 
Able to be reproduced? (Yes/No): No

What is the problem and how can it be reproduced?

Does not display the message “No Bookmark found” when there are no bookmarks found in the mobile.

     Reported By: Pooja Raghoji 	Date: 04/10/2015
~~~~~~~~~~~~~~~~~~~~~ DEVELOPMENT TEAM ONLY ~~~~~~~~~~~~~~~~~~~~~

Functional Area: ____________________________	Assigned To: ____________________

Comments: ___________________________________________________________________________
___________________________________________________________________________

Status (Open/Closed): _____________________	Priority (1-5): __________________

Resolution (Pending, Fixed, Irreproducible, Reassigned, As Intended, Unfixable, Withdrawn, Requesting More Information, Disagree with Suggestion): ___________________________

Resolved By: _______________________	Date: ________________

Tested By: _________________________	Date: ________________

Fixed Version Number: ______________________

**Comment by srowen** [comment] 2015-05-14 07:48
This is misdirected. There is no real content to these issue reports, and I'm only accepting pull requests for easy, clear bugs now. Please don't file more.

**Closed by srowen** 2015-05-14 07:48 UTC
