### ISSUE TITLE
Maxicode decoding result raw bytes is missing error correction codewords

### ISSUE THREAD

**Issue by gredler** [zxing/zxing#429] opened 2015-07-22 16:23 UTC
Decoding the image below with this code:

    LuminanceSource source = new BufferedImageLuminanceSource(img);
    BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
    Map< DecodeHintType, Boolean > hints = Collections.singletonMap(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
    Result result = reader.decode(bitmap, hints);
    byte[] bytes = result.getRawBytes();

Results in the following raw byte (codeword) array:

[4, 1, 2, 3, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33]

However, the two sections of error correction codewords are missing. Expected raw byte array:

[4, 1, 2, 3, 33, 33, 33, 33, 33, 33, **13, 1, 28, 60, 35, 56, 0, 48, 52, 15,** 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33**, 60, 60, 40, 40, 9, 9, 43, 43, 14, 14, 50, 50, 12, 12, 53, 53, 57, 57, 58, 58, 36, 36, 28, 28, 10, 10, 53, 53, 37, 37, 30, 30, 14, 14, 5, 5, 31, 31, 40, 40**]

![mode-4-basic-structured-append-total-1](https://cloud.githubusercontent.com/assets/178883/8830700/a3a621d0-306b-11e5-899c-4717ff949ee9.png)

**Comment by srowen** [comment] 2015-07-22 20:40
So, it's not always clear what 'raw bytes' should return since some barcodes have nothing that might be called an underlying byte representation. For some, like this or QR codes there are several layers: raw code words, after error correction is parsed, after the bit stream is parsed, after the bytes are parsed as characters. For QR codes I use the result post error correction. My theory is people don't really want to also do the error correction by hand, but may want to access the raw encoding from that point after. so I'd provisionally close this as working as intended. If needed you can hack the code to do most anything you need.

**Closed by srowen** 2015-07-22 20:40 UTC

**Comment by travisfw** [comment] 2015-07-23 22:39
ZXing doesn't seem to support MaxiCode at all now. Is this functionality deprecated? If so, why, and will it come back?
