### ISSUE TITLE
Zxing 3.3.1 - Crashes on Android lower API 19

### ISSUE THREAD

**Issue by micsha123** [zxing/zxing#946] opened 2018-01-22 03:12 UTC
I use `Zxing` library in my app with min API = 14.
Yesterday I changed version of `Zxing` from 3.3.0 to 3.3.1 - and for today I've got crashes on API < 19:

```
Fatal Exception: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
       at com.google.zxing.pdf417.decoder.DecodedBitStreamParser.decode(DecodedBitStreamParser.java:96)
       at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:534)
       at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:309)
       at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:278)
       at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:124)
       at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
       at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
```

Could you return to previous case or change this part of code:

```
  static DecoderResult decode(int[] codewords, String ecLevel) throws FormatException {
       StringBuilder result = new StringBuilder(codewords.length * 2);
       Charset encoding = StandardCharsets.ISO_8859_1;     <---- crashes/ https://stackoverflow.com/questions/38183027/java-lang-noclassdeffounderror-java-nio-charset-standardcharsets
       // Get compaction mode
       int codeIndex = 1;
```

Thanks in advance!

**Comment by srowen** [comment] 2018-01-22 04:17
No, won't change that. It wouldn't fix it anyway. This is a duplicate of https://github.com/zxing/zxing/issues/937

**Closed by srowen** 2018-01-22 04:17 UTC
