### ISSUE TITLE
Scan via Chrome browser URL seems to cache redirect and return to wrong location

### ISSUE THREAD

**Issue by Tzvetelin88** [zxing/zxing#400] opened 2015-06-07 15:25 UTC
I am developing web application for custom scan and search products from custom database. 
It seems that zxing cache and redirect to wrong location.
I made a test with that link: http://www.tx9.co.uk/zxingtest.php on my:
Nexus 5 android 5.1.1 and
Asus MemoPad HD7 4.4.2

but still redirects to wrong location. For example:
When a go to a.php and scan - redirect to a.php
after that I go to b.php and scan - redirect to b.php
after that I go to a.php and scan - redirect to b.php - Not correct.

I cleared cache but still not working correctly.

I even tested that build : https://drive.google.com/file/d/0B_hfrkaWlLi4cVd2WWEtb21FTzA/view?usp=sharing  

but result is the same.

**Comment by srowen** [comment] 2015-06-07 15:26
This is a duplicate of https://github.com/zxing/zxing/issues/302

**Closed by srowen** 2015-06-07 15:26 UTC

**Comment by Tzvetelin88** [comment] 2015-06-07 15:30
Hello Srowen, yes it seem to.
But I tried that build of Zxing application, and still redirects to wrong place.

**Comment by srowen** [comment] 2015-06-07 15:31
No, I've tested this case and we both confirmed it's fixed. I think you actually aren't using the new build.

**Comment by Tzvetelin88** [comment] 2015-06-07 15:34
Is this the link to the new build:   https://drive.google.com/file/d/0B_hfrkaWlLi4cVd2WWEtb21FTzA/view?usp=sharing  ? because I just tested it on my Nexus 5 Android 5.1.1  and redirects me to the wrong place.
 Is there anything else that I need to do except installation ?

**Comment by Tzvetelin88** [comment] 2015-06-09 06:03
Hello srowen, I made I test with the new build given here: https://github.com/zxing/zxing/issues/302 
also on my Tablet (Asus Memo 7, Android 4.4.1 with chrome 43.0.2357.92 )  
and I can confirmed that it stills redirect to the wrong place.

**Comment by srowen** [comment] 2015-06-09 07:23
OK, can you submit a pull request for what you think is wrong? I am not able to work on reproducing this, and can't reproduce it anyway.

**Comment by Tzvetelin88** [comment] 2015-06-09 14:05
I made a couple of tests on my Asus memo pad 7:
First test:

Chrome Version:  36.0.1985.135
Android Version :  4.4.2

When I go to scan a barcode and get back to php file I notice that barcode scanner doesn't stay open it's closed automatically. 

If you make new scan, barcode scanner opens again and after scan it's closes.

But this is only on old chrome version like 36.
--------------------------------------------------------------------------------------------
Second test:
Chrome Version:  43.0.2357.92
Android Version :  4.4.2

Barcode scanner stays open no matter what and when you returned from scan, it redirects you to the wrong place.


I think one of the fixes for this case could be:
If there is an option to close barcode scanner after successful scan and returned to php, just like old version of chrome 36 could resolve this problem.

**Comment by cramarc85** [comment] 2015-09-08 16:45
why is it closed?
the problem is still there :(

i've tried it with the newest version from the market and still redirected to the wrong url. the sprintf solution doesn't work.

if there is an option to close the application (Tzvetelin88's solution), it would be great and could fix the hole problem

**Comment by cramarc85** [comment] 2015-09-08 16:54
there is no problem with firefox... it closes the app automatically... chrome doesn't

**Comment by mithuns14** [comment] 2016-08-31 03:55
how to return zxing barcode result back to actual caller(if it calls from Chrome, it should only return to same browser)?
